# name: lrru2
# channels:
#   - defaults
#   - conda-forge
#   - nvidia
#   - pytorch
# dependencies:
#   - python=3.9
#   - cudatoolkit=11.8
#   - cudnn=8.8.0
#   - pytorch=1.7.1
#   - torchvision=0.8.2
#   - pip

name: lrru3
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.8
  - cudatoolkit=11.8
  - cudnn=8.8.0
  - pytorch=1.6.0
  - torchvision=0.8.0
  - pip